development:
  adapter: mysql2
  database: xlsx_talk_development
  pool: 8
  username: root
  password: 
test:
  adapter: mysql2
  database: xlsx_talk_test
  pool: 5
  timeout: 5000
  username: root
  password:

production:
  adapter: pg
  database: xlsx_talk_production
  pool: 5
  timeout: 5000
  username: root
